### ISSUE TITLE
Add more file extensions.

### ISSUE THREAD

**Issue by vasil7112** [tres-framework/Tres-package-manager#2]
Although .php is fine with most of the files, alot of users might have some other types too.
Such as .class.php, .cron.php, .ped.php.
You could add an extra parameter into the function that allows the user to add a custom extension such as the above.

Kind regards,
vasil7112

**Comment by pedzed** [comment]
In my opinion it's bad practice to use anything other than `.class.php` and `.php`, but I added two methods anyway which let you add your own extensions.

The default is `.php`. You can add more by using `addExtension` or `addExtensions`:

``` php
$autoloader->addExtension('.cls.php');
$autoloader->addExtension('.phpclass');
$autoloader->addExtensions([
    '.class',
    '.class.php'
]);
```

Could you try it and give your opinion about it?
